### ISSUE TITLE
Broadlink SP Mini devices

### ISSUE THREAD

**Issue by mattie47** [lprhodes/homebridge-broadlink-rm#165]
Hi,

I just wanted to double check that this plugin is only for the RM devices, and not also the SP mini smart plugs?

Thanks,

Matt

**Comment by astrojetson8** [comment]
That's correct.
For SP mini smart plugs there's another plugin.

**Comment by jkerdsri** [comment]
Can we install two plugins for both RM and SP mini?

**Comment by fotanski** [comment]
I think so，u can get them done well

**Comment by nico81** [comment]
Which one is for SPmini? I can't find it

**Comment by mattie47** [comment]
@nico81  I simply moved to using https://home-assistant.io/ instead, and integrated homebridge into it.

That way, config of my broadlink devices is done in home-assistant, but also available in homebridge.

**Homebridge config**

```
osmc:/home/homeassistant/.homebridge$ cat config.json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CD:21:3D:E3:CE:40",
        "port": 51826,
        "pin": "111-11-111"
    },


"platforms": [
  {
    "platform": "HomeAssistant",
    "name": "HomeAssistant",
    "host": "http://127.0.0.1:8123",
    "password": "removed",
    "supported_types": ["automation", "binary_sensor", "climate", "cover", "device_tracker", "fan", "group", "input_boolean", "light", "lock", "media_player", "remote", "scene", "sensor", "switch"],
    "default_visibility": "visible",
    "logging": true,
    "verify_ssl": false
  }
]
}

```

**Home Assistant config**
Some output omitted.
```
switch:
  - platform: broadlink
    host: 192.168.1.32
    mac: '34:EA:8:1F:'
    friendly_name: "plug"
    type: sp3
    update_interval: 60
  - platform: broadlink
    host: 192.168
    mac: '34:EA:34::26'
    type: sp3
    friendly_name: "Heater"
    update_interval: 60

```

You can find more info on home-assistants website.
